# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

#[[main]]
  #name = "Home"
  #url = "#intro"
  #weight = 5

[[main]]
  name = "Call for Papers"
  url = "#calls"
  weight = 15

[[main]]
  name = "Reading"
  url = "#reading"
  weight = 25

#[[main]]
  #name = "Schedule"
  #url = "#schedule"
  #weight = 30

[[main]]
  name = "Organizers"
  url = "#people"
  #url = "#organizer"
  weight = 50

[[main]]
  name = "Program"
  url = "#program"
  weight = 60

[[main]]
  name = "Accepted Papers"
  url = "#accepted_papers"
  weight = 70

[[main]]
  name = "Sponsors"
  url = "#sponsors"
  weight = 80


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
